### ISSUE TITLE
Calculation of Sampling Rates Not Correct in get_channel_table

### ISSUE THREAD

**Issue by shanlyMIDE** [MideTechnology/endaq-python-ide#17]
It looks like sampling rates are being calculated by taking the full time delta and dividing it by the total number of samples. It should be dividing by (n-1) because that represents the number of steps.

It is a pretty small difference but something we should fix. I believe this error is in the Lab too in the recording properties area.

**Comment by StokesMIDE** [comment]
@shanlyMIDE I think this was fixed in 1.1.0; can you check?

**Comment by S-Hanly** [comment]
Yep!
