### ISSUE TITLE
Fix Dependency Issue with Pandas

### ISSUE THREAD

**Issue by shanlyMIDE** [MideTechnology/endaq-python-ide#28]
When installing endaq we should be checking the libraries we use and updating them if necessary. It seems we need pandas 1.3.1 or later, 1.3.2 and 1.3.3 seem to work as well.

https://colab.research.google.com/drive/1HdUhgVK2nXMTat0nTXDFcPGC58vMTbA5#scrollTo=XH_cw624vgdw

Note this isn't a colab thing, the first time I downloaded endaq on my local machine and tried to run it I also needed to update pandas.

**Comment by shanlyMIDE** [comment]
I see this is updated in the dev branch, but @StokesMIDE do we want to update our idelib requirement to be 3.2.3 not 3.2.2?

cc: @pscheidler

**Comment by StokesMIDE** [comment]
It should be 3.2.3, but it isn't critical; the requirement is `idelib>=3.2.2`, so any fresh install will get 3.2.3.

**Comment by S-Hanly** [comment]
Corrected in latest release
