### ISSUE TITLE
get_channel_table fails on Python < 1.3

### ISSUE THREAD

**Issue by pscheidler** [MideTechnology/endaq-python-ide#32]
```
import endaq.ide
fn = "../IDE/SSX10386_063.ide"
doc = endaq.ide.get_doc(fn)
endaq.ide.get_channel_table(doc)
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python38\lib\site-packages\endaq\ide\info.py", line 289, in get_channel_table
    styled = pd.DataFrame(result).style.format(style, precision=precision)
TypeError: format() got an unexpected keyword argument 'precision'

Can we update the requirements to call for Python >= 1.3?

**Comment by StokesMIDE** [comment]
@pscheidler Do you mean Pandas 1.3?
